package constants

const (
	//trade type
	TRADE_TYPE_BASE = iota
	TRADE_TYPE_MINER
	TRADE_TYPE_RECHARGE
	TRADE_TYPE_WITHDRAWAL
	TRADE_TYPE_TRANSFER
	TRADE_TYPE_PAY
	TRADE_TYPE_FEE
	TRADE_TYPE_REFUND
	TRADE_TYPE_LIQUIDATED_DAMAGES
	TRADE_TYPE_REWARD
	TRADE_TYPE_ADVERTISING_FEE
	TRADE_TYPE_CONVERSION
	TRADE_TYPE_OTHER = 99
)

const (
	//trade status
	TRADE_STATUS_WAIT_PROCESS = iota
	TRADE_STATUS_PROCESSING
	TRADE_STATUS_SUCC
	TRADE_STATUS_FAILED
	TRADE_STATUS_TIMEOUT
	TRADE_STATUS_CLOSE
	TRADE_STATUS_REFUND
)

const (
	//trade sub type
	TX_SUB_TYPE_ALL                         = 0
	TX_SUB_TYPE_WAGE                        = 1
	TX_SUB_TYPE_PRIVATE_PLACEMENT           = 2
	TX_SUB_TYPE_ACTIVITY_REWARD             = 3
	TX_SUB_TYPE_TRANS                       = 4
	TX_SUB_TYPE_RECEIVABLES                 = 5
	TX_SUB_TYPE_LOCKD_LIQUIDATED_DAMAGES    = 6
	TX_SUB_TYPE_MERCHANT_LIQUIDATED_DAMAGES = 8
	TX_SUB_TYPE_REFUND                      = 10
	TX_SUB_TYPE_WITHDRAW                    = 11
	TX_SUB_TYPE_WITHDRAW_RETURN             = 12
	TX_SUB_TYPE_BUY                         = 13
	TX_SUB_TYPE_AUTH_TRANSFER               = 14
	TX_SUB_TYPE_ASSET_CONV                  = 15
	TX_SUB_TYPE_AUTH_TRANSFER_REFUND_FEE    = 16
	TX_SUB_TYPE_BUY_REFUND_FEE              = 17
	TX_SUB_TYPE_WITHDRAW_RETURN_FEE         = 18
	TX_SUB_TYPE_RECHANGE                    = 21
	TX_SUB_TYPE_WITHDRAW_FEE                = 22
	TX_SUB_TYPE_TRANSFER_FEE                = 24
	TX_SUB_TYPE_AUTH_TRANSFER_FEE           = 26
	TX_SUB_TYPE_BUY_FEE                     = 27
	TX_SUB_TYPE_MERCHANT_FEE                = 28
	TX_SUB_TYPE_ASSET_CONV_FEE              = 29
	TX_SUB_TYPE_WAGE_OF_DAY_PAY_SUM         = 198
	TX_SUB_TYPE_WAGE_OF_DAY_PAY_DESTROY     = 199
)

const (
	//other
	TRADE_DECIMAIL      = 8
	TRADE_EOS_DECIMAIL  = 4
	TRADE_CURRENCY_LVT  = "LVT"
	TRADE_CURRENCY_LVTC = "LVTC"
	TRADE_CURRENCY_ETH  = "ETH"
	TRADE_CURRENCY_BTC  = "BTC"
	TRADE_CURRENCY_EOS  = "EOS"
)
