package constants

const (
	//trade type
	TRADE_TYPE_BASE = iota
	TRADE_TYPE_MINER
	TRADE_TYPE_RECHARGE
	TRADE_TYPE_WITHDRAWAL
	TRADE_TYPE_TRANSFER
	TRADE_TYPE_PAY
	TRADE_TYPE_FEE
	TRADE_TYPE_REFUND
	TRADE_TYPE_LIQUIDATED_DAMAGES
	TRADE_TYPE_REWARD
	TRADE_TYPE_ADVERTISING_FEE
)

